package 'vim'
package 'build-essential'
package 'libssl-dev'
package 'libreadline-dev'
package 'zlib1g-dev'
package 'nodejs'
package 'libpq-dev'
package 'git'

include_recipe '../cookbooks/users/default.rb'
